version: '2'
services:
  jenkins2:
    image: willoucom/jenkins2-docker
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      - soccat
    volumes:
      - data:/var/jenkins_home
  soccat:
    image: willoucom/socat-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  data:
